routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

Route::get('/', 'HomeController@index');
Route::get('/widgets/{id}', 'HomeController@getWidget')->name('widgets');

Route::get('/atividade/cadastro', 'ActivitiesController@register');
Route::get('/atividade/{id}', 'ActivitiesController@details')->name('activity.details');
Route::post('/atividades/novo', 'ActivitiesController@store')->name('activity.store');
Route::delete('/atividades/{id}', 'ActivitiesController@destroy');
Route::get('/atividades', 'ActivitiesController@index')->name('activity.index');


Route::get('/departamento/{slug}', 'NewsController@index')->name('news.departament');
Route::post('/noticia/comment', 'NewsController@comment')->name('news.comment');
Route::get('/noticia/{slug}', 'NewsController@details')->name('new.details');
Route::get('/noticias', 'NewsController@index')->name('news');

Route::get('/evento/{slug}', 'EventsController@details')->name('event.details');
Route::get('/eventos', 'EventsController@index')->name('events');


Route::get('/produtos/{id}', 'ProductsController@details')->name('product.details');
Route::get('/produtos', 'ProductsController@index');

Route::get('/links-importantes', 'LinksController@index');

Route::get('/contra-cheques/visualizacao/{filename}', 'PaychecksController@view')->name('paycheck.view');
Route::get('/contra-cheques/download/{filename}', 'PaychecksController@download')->name('paycheck.download');
Route::get('/rh-contra-cheques', 'PaychecksController@index');

Route::get('/aniversariantes', 'BirthsController@index')->name('births.index');

Route::put('/documentos/delete', 'DocumentsController@delete');
Route::put('/documentos/rename', 'DocumentsController@rename');
Route::put('/documentos/move', 'DocumentsController@move');
Route::put('/documentos/copy', 'DocumentsController@copy');
Route::get('/documentos/download', 'DocumentsController@download');
Route::post('/documentos/folder', 'DocumentsController@folder');
Route::post('/documentos/upload', 'DocumentsController@upload');
Route::get('/documentos/directories', 'DocumentsController@getDirectories');
Route::get('/documentos/root', 'DocumentsController@all');
Route::get('/documentos', 'DocumentsController@index');

Route::get('me', function(){
	return response()->json([
		'isAdmin' => Auth::user()->hasRole(['ti', 'admin', 'diretoria']),
		//'roles' => Auth::user()->roles->map(function($role){ return $role->name; }),
		//'departaments' => Auth::user()->collaborator->departaments,
	], 200, [], JSON_PRETTY_PRINT);
});

Route::resource('/clientes', 'ClientsController');

//rota extra ATENÇÃO
Route::get('/paychecks/download', 'Admin\PaychecksController@download');


Route::get('meu-perfil', 'ProfileControler@index')
				->name('profile')
				->middleware('auth');

Route::post('meu-perfil', 'ProfileControler@changePassword')
				->name('profile_post')
				->middleware('auth');

Auth::routes();
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/admin', 'Admin\AdminController@index');

// Adicionado por Samuel Edson

Route::namespace('Intranet')->prefix('intranet')->group(function () {

    Route::prefix('auth')->group(function () {

        Route::get('login', 'AuthController@login')->name('intranet.auth.login');
        Route::post('login', 'AuthController@authenticate')->name('intranet.auth.login');
        Route::get('logout', 'AuthController@logout')->name('intranet.auth.logout');

    });

    Route::get('/', 'HomeController@home')->name('intranet.home');

    Route::middleware('auth')->group(function () {

        Route::get('teste', 'HomeController@teste')->name('intranet.teste');

        Route::prefix('roles')->middleware('permission:roles')->group(function () {

            Route::get('/', 'RoleController@index')
                ->name('intranet.roles.index');

            Route::get('show/{id?}', 'RoleController@show')
                ->name('intranet.roles.show');

            Route::post('store', 'RoleController@store')
                ->name('intranet.roles.store');

            Route::get('destroy/{id?}', 'RoleController@destroy')
                ->name('intranet.roles.destroy');

        });

        Route::prefix('departaments')->middleware('permission:departaments')->group(function () {

            Route::get('/', 'DepartamentController@index')
                ->name('intranet.departaments.index');

            Route::get('show/{id?}', 'DepartamentController@show')
                ->name('intranet.departaments.show');

            Route::post('store', 'DepartamentController@store')
                ->name('intranet.departaments.store');

            Route::get('destroy/{id?}', 'DepartamentController@destroy')
                ->name('intranet.departaments.destroy');

        });

        Route::prefix('products')->middleware('permission:products')->group(function () {

            Route::get('/', 'ProductController@index')
                ->name('intranet.products.index');

            Route::get('show/{id?}', 'ProductController@show')
                ->name('intranet.products.show');

            Route::post('store', 'ProductController@store')
                ->name('intranet.products.store');

            Route::get('destroy/{id?}', 'ProductController@destroy')
                ->name('intranet.products.destroy');

        });

        Route::prefix('categories')->middleware('permission:products')->group(function () {

            Route::get('/', 'CategoryController@index')
                ->name('intranet.categories.index');

            Route::get('show/{id?}', 'CategoryController@show')
                ->name('intranet.categories.show');

            Route::post('store', 'CategoryController@store')
                ->name('intranet.categories.store');

            Route::get('destroy/{id?}', 'CategoryController@destroy')
                ->name('intranet.categories.destroy');

        });

        Route::prefix('indications')->middleware('permission:indications')->group(function () {

            Route::prefix('status')->middleware('permission:indication-status')->group(function () {

                Route::get('/', 'IndicationStatusController@index')
                    ->name('intranet.indications.status.index');

                Route::get('show/{id?}', 'IndicationStatusController@show')
                    ->name('intranet.indications.status.show');

                Route::post('store', 'IndicationStatusController@store')
                    ->name('intranet.indications.status.store');

                Route::get('destroy/{id?}', 'IndicationStatusController@destroy')
                    ->name('intranet.indications.status.destroy');

            });

            Route::get('/', 'IndicationController@index')
                ->name('intranet.indications.index');

            Route::get('by-me', 'IndicationController@byMe')
                ->name('intranet.indications.byme');

            Route::get('create', 'IndicationController@create')
                ->name('intranet.indications.create')
                ->middleware('permission:indications-create');

            Route::post('/', 'IndicationController@store')
                ->name('intranet.indications.store')
                ->middleware('permission:indications-create');

            Route::get('/{id}', 'IndicationController@show')
                ->name('intranet.indications.show');

            Route::put('/{id}', 'IndicationController@update')
                ->name('intranet.indications.update')
                ->middleware('permission:indications-update');

            Route::post('/transfer-propection', 'IndicationController@transferPropecting')
                ->name('intranet.indications.transfer-propection')
                ->middleware('permission:indications-update');

            Route::get('{id?}/destroy', 'IndicationController@destroy')
                ->name('intranet.indications.destroy')
                ->middleware('permission:indications-delete');

            Route::post('client/verify', 'ClientController@getClient')
                ->name('intranet.indications.client.verify');

            Route::post('client/products-indicated', 'ClientController@getProductsIndicated')
                ->name('intranet.indications.client.product_options');

        });

        Route::prefix('productions')->middleware('permission:productions')->group(function () {

            Route::get('/', 'ProductionController@index')
                ->name('intranet.productions.index');

            Route::get('manager', 'ProductionController@manager')
                ->name('intranet.productions.manager')
                ->middleware('permission:productions-manager');

            Route::get('create', 'ProductionController@create')
                ->name('intranet.productions.create')
                ->middleware('permission:productions-create');

            Route::post('/', 'ProductionController@store')
                ->name('intranet.productions.store')
                ->middleware('permission:productions-create');

            Route::get('/{id?}', 'ProductionController@show')
                ->name('intranet.productions.show');

            Route::get('edit/{id?}', 'ProductionController@edit')
                ->name('intranet.productions.edit')
                ->middleware('permission:productions-update');

            Route::put('/{id}', 'ProductionController@update')
                ->name('intranet.productions.update')
                ->middleware('permission:productions-update');

app/Http/Controllers/Admin/ClientsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;
use App\Http\Requests\ClientCreateRequest;
use App\Http\Requests\ClientUpdateRequest;
use App\Repositories\ClientRepository;
use App\Validators\ClientValidator;


class ClientsController extends Controller
{

    /**
     * @var ClientRepository
     */
    protected $repository;

    /**
     * @var ClientValidator
     */
    protected $validator;

    public function __construct(ClientRepository $repository, ClientValidator $validator)
    {
        $this->repository = $repository;
        $this->validator  = $validator;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->repository->pushCriteria(app('Prettus\Repository\Criteria\RequestCriteria'));
        $clients = $this->repository->all();

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $clients,
            ]);
        }

        return view('clients.index', compact('clients'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  ClientCreateRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(ClientCreateRequest $request)
    {

        try {

            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_CREATE);

            $client = $this->repository->create($request->all());

            $response = [
                'message' => 'Client created.',
                'data'    => $client->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->back()->with('message', $response['message']);
        } catch (ValidatorException $e) {
            if ($request->wantsJson()) {
                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }


    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $client = $this->repository->find($id);

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $client,
            ]);
        }

        return view('clients.show', compact('client'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $client = $this->repository->find($id);

        return view('clients.edit', compact('client'));
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  ClientUpdateRequest $request
     * @param  string            $id
     *
     * @return Response
     */
    public function update(ClientUpdateRequest $request, $id)
    {

        try {

            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_UPDATE);

            $client = $this->repository->update($request->all(), $id);

            $response = [
                'message' => 'Client updated.',
                'data'    => $client->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->back()->with('message', $response['message']);
        } catch (ValidatorException $e) {

            if ($request->wantsJson()) {

                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $deleted = $this->repository->delete($id);

        if (request()->wantsJson()) {

            return response()->json([
                'message' => 'Client deleted.',
                'deleted' => $deleted,
            ]);
        }

        return redirect()->back()->with('message', 'Client deleted.');
    }
}

app/Http/Controllers/Intranet/ClientController.php
<?php

namespace App\Http\Controllers\Intranet;

use App\Repositories\ClientRepository;
use App\Repositories\ProductRepository;
use App\Validators\ClientValidator;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

/**
 * Class ClientController
 * @package App\Http\Controllers\Intranet
 */
class ClientController extends Controller
{

    /**
     * @var ClientRepository
     */
    private $repository;

    /**
     * @var ClientValidator
     */
    private $validator;

    /**
     * ClientController constructor.
     * @param ClientRepository $repository
     * @param ClientValidator $validator
     */
    public function __construct(ClientRepository $repository, ClientValidator $validator)
    {
        $this->repository = $repository;
        $this->validator = $validator;
    }


    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function getClient(Request $request){

        $client = $this->repository;

        $where = [];

        if(!empty($request->input('type_profile')))
            $where['type_profile'] = $request->input('type_profile');

        if(!empty($request->input('cpf')))
            $where['cpf'] = str_replace(['.', '-'], '', $request->input('cpf'));

        if(!empty($request->input('cnpj')))
            $where['cnpj'] = str_replace(['.', '/', '-'], '', $request->input('cnpj'));

        if(!empty($where))
            $client = $client->findWhere($where);

        return response()->json($client->first());

    }

    public function getProductsIndicated(Request $request){

        return response()->json(
            $this->repository
                ->getProductsIndicated($request->input('client_id'))
        );

    }

}

resources/views/clients/edit.blade.php
<form name="formCliente" id="formCliente">
	{{ csrf_field() }}
	<div class="row">
		<div class="col-sm-6">
			<h4>Dados de Contato</h4>
		  <div class="form-group">    
		    <label class="radio-inline">
				  <input type="radio" name="type_profile" value="J" {{ $client->type_profile == 'J' ? 'checked' : null  }}> Pessoa Jurídica
				</label>

		    <label class="radio-inline">
				  <input type="radio" name="type_profile" value="F" {{ $client->type_profile == 'F' ? 'checked' : null  }}> Pessoa Fisica
				</label>
		  </div>

		  <div class="form-group" id="cpf" style="display: none">
		    <label for="cpf">CPF</label>
		    <input type="text" class="form-control cpf" name="cpf" placeholder="CPF" value="{{$client->cpf}}" maxlength="14" />
		  </div>

		  <div class="form-group" id="cnpj">
		    <label for="cnpj">CNPJ</label>
		    <input type="text" class="form-control cnpj" name="cnpj" placeholder="CNPJ" value="{{$client->cnpj}}" maxlength="18" />
		  </div>

			<div class="form-group" id="company_name">
		    <label for="company_name">Nome da Empresa</label>
		    <input type="text" class="form-control" name="company_name" value="{{$client->company_name}}" />
		  </div>

		  <div class="form-group">
		    <label for="name">Nome de Contato</label>
		    <input type="text" class="form-control" name="name" value="{{$client->name}}" />
		  </div>

			<div class="form-group">
		    <label for="email">E-mail</label>
		    <input type="text" class="form-control" name="email" value="{{$client->email}}" />
		  </div>
			
			<div class="form-group">
		    <label for="cellphone">Celular</label>
		    <div class="row">
			    <div class="col-xs-12 col-sm-4">
						<input type="text" class="form-control celphones" name="cellphone" value="{{$client->cellphone}}" placeholder="Celular" />
			    </div>
			    <div class="col-xs-12 col-sm-4">
						<input type="text" class="form-control celphones" name="phone1" value="{{$client->phone1}}" placeholder="Telefone 1" />
			    </div>
			    <div class="col-xs-12 col-sm-4">
						<input type="text" class="form-control celphones" name="phone2" value="{{$client->phone2}}" placeholder="Telefone 2" />
			    </div>
		    </div>	    
		  </div>
		</div>
		<div class="col-sm-6">
			<h4>Dados de Endereço</h4>
			<div class="form-group">
		    <label for="postcode">CEP</label>
		    <input type="text" class="form-control postcode" name="postcode" value="{{$client->postcode}}" maxlength="9" style="max-width: 150px" />
		  </div>

			<div class="form-group">
		    <label for="address">Endereço</label>
		    <div class="row">
			    <div class="col-sm-8">
			    	<input type="text" class="form-control pull-left" value="{{$client->address}}" name="address" />
			    </div>
			    <div class="col-sm-4">
			    	<input type="text" class="form-control pull-right" name="number" value="{{$client->number}}" placeholder="Número"/>
			    </div>
		    </div>
		  </div>

		  <div class="form-group">
		    <label for="district">Bairro</label>
		    <input type="text" class="form-control" name="district" value="{{$client->district}}" />
		  </div>

		  <div class="form-group">
		    <label for="complement">Complemento</label>
		    <input type="text" class="form-control" name="complement" value="{{$client->district}}" />
		  </div>

		  <div class="form-group">
		    <label for="state">Estado - Cidade</label>
		    <div class="row">
		    	<div class="col-sm-4">
				    <select name="state" class="form-control">
				    	<option value="">Estado</option>
							<option value="AC" {{ $client->state == 'AC' ? 'selected' : null  }}>Acre</option>
							<option value="AL" {{ $client->state == 'AL' ? 'selected' : null  }}>Alagoas</option>
							<option value="AP" {{ $client->state == 'AP' ? 'selected' : null  }}>Amapá</option>
							<option value="AM" {{ $client->state == 'AM' ? 'selected' : null  }}>Amazonas</option>
							<option value="BA" {{ $client->state == 'BA' ? 'selected' : null  }}>Bahia</option>
							<option value="CE" {{ $client->state == 'CE' ? 'selected' : null  }}>Ceará</option>
							<option value="DF" {{ $client->state == 'DF' ? 'selected' : null  }}>Distrito Federal</option>
							<option value="ES" {{ $client->state == 'ES' ? 'selected' : null  }}>Espírito Santo</option>
							<option value="GO" {{ $client->state == 'GO' ? 'selected' : null  }}>Goiás</option>
							<option value="MA" {{ $client->state == 'MA' ? 'selected' : null  }}>Maranhão</option>
							<option value="MT" {{ $client->state == 'MT' ? 'selected' : null  }}>Mato Grosso</option>
							<option value="MS" {{ $client->state == 'MS' ? 'selected' : null  }}>Mato Grosso do Sul</option>
							<option value="MG" {{ $client->state == 'MG' ? 'selected' : null  }}>Minas Gerais</option>
							<option value="PA" {{ $client->state == 'PA' ? 'selected' : null  }}>Pará</option>
							<option value="PB" {{ $client->state == 'PB' ? 'selected' : null  }}>Paraíba</option>
							<option value="PR" {{ $client->state == 'PR' ? 'selected' : null  }}>Paraná</option>
							<option value="PE" {{ $client->state == 'PE' ? 'selected' : null  }}>Pernambuco</option>
							<option value="PI" {{ $client->state == 'PI' ? 'selected' : null  }}>Piauí</option>
							<option value="RJ" {{ $client->state == 'RJ' ? 'selected' : null  }}>Rio de Janeiro</option>
							<option value="RN" {{ $client->state == 'RN' ? 'selected' : null  }}>Rio Grande do Norte</option>
							<option value="RS" {{ $client->state == 'RS' ? 'selected' : null  }}>Rio Grande do Sul</option>
							<option value="RO" {{ $client->state == 'RO' ? 'selected' : null  }}>Rondônia</option>
							<option value="RR" {{ $client->state == 'RR' ? 'selected' : null  }}>Roraima</option>
							<option value="SC" {{ $client->state == 'SC' ? 'selected' : null  }}>Santa Catarina</option>
							<option value="SP" {{ $client->state == 'SP' ? 'selected' : null  }}>São Paulo</option>
							<option value="SE" {{ $client->state == 'SE' ? 'selected' : null  }}>Sergipe</option>
							<option value="TO" {{ $client->state == 'TO' ? 'selected' : null  }}>Tocantins</option>	
				    </select>
			    </div>
			    <div class="col-sm-8">
						<input type="text" class="form-control" name="city" placeholder="Cidade" value="{{$client->city}}" />
			    </div>
		    </div>
		  </div>
		</div>
	</div>
</form>

<div class="modal-footer">
  <button type="button" class="btn btn-default" style="color: #FFF; background-color: #CCC; border-color: #ccc; margin-right: 5px;" data-dismiss="modal">Cancelar</button>
  <button type="button" class="btn btn-primary save">Salvar</button>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$('[name="type_profile"]').on('change', function(){
			var val = $(this).val()
			if(val === 'J'){
				$('#cnpj').css('display', 'block');
				$('#company_name').css('display', 'block');
				$('#cpf').css('display', 'none');

				
				$('[name="cpf"]').val('');
			} else {
				$('#cnpj').css('display', 'none');
				$('#company_name').css('display', 'none');
				$('#cpf').css('display', 'block');

				$('[name="cnpj"]').val('');
			}
		});

		$('.save').on('click', function(){
			$.ajax({
			  url: "{{ route('clientes.update', ['id' => $client->id]) }}",
			  method: "PUT",
			  dataType: 'json',
			  data: $('#formCliente').serialize(),
			  success: function(res){
			  	if($('#modal').length){
			      var mySelect = $('#client_id');
			    
			     	window.location = '{{{ route('clientes.index') }}}';

			      
			  	}
			  	
			  },
			  error: function(jqXHR, textStatus, errorThrown) {
			  	if(jqXHR.status === 422){
				  	var response = jqXHR.responseJSON;
				  	var el;
			    	$.each(response, function(index, item){
			    		el = $('input[name="'+index+'"]');
			    		el.parent().addClass('has-error');
			    		
			    		el.parent().find(".help-block").remove();

			    		$.each(item, function(i, message){
								el.parent().append('<p class="help-block">'+message+'</p>')
			    		})
			    	});	
			  	}
		    	
			  }
			});
		})
	})
</script>

resources/views/clients/index.blade.php
@extends('layouts.sicoob.default')

@section('arquivos_estilos')
<link rel="stylesheet" href="/css/jquery-ui.css">
@endsection

@section('arquivos_scripts')
<script src="/js/jquery.meio.mask.min.js"></script>
  <script src="/js/jquery-ui.js"></script>
@endsection

@section('blocos_script')

  $('.remove').on('click', function(){
    var id = $(this).data('id');

    swal({
      title: 'Tem certeza que deseja excluir?',
      type: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#00a091',
      confirmButtonText: 'Sim!',
      cancelButtonText: 'Não'
    }).then(function () {
     $.ajax({
          url: '/clientes/'+id,
          type: 'DELETE',
          headers: {
                'X-CSRF-TOKEN' : Laravel.csrfToken
          },
          success: function(result) {
            swal(
              'Sucesso!',
              'Atividade removida com Sucesso!',
              'success'
            ).then(function(){
              window.location = "{{{ route('clientes.index') }}}"
            })
          }
      });
    })
  })
  
@endsection

@section('content')
  <div class="fundo-branco sombra-caixa ctn-atividades">
    <div class="row">
      <div class="col-sm-6">
        <h1 class="titulo-janelas">
          <i class="icomoon icon-cog-outline"></i>
          <div>CLIENTES</div>
        </h1>
      </div>

      <div class="col-sm-6 text-right">
        <a href="javascript:void(0)" 
           onclick="SximoModal('{{{ route('clientes.create', ['list' => true] ) }}}', 'Cadastro de Clientes')" 
           title="Adicionar Cliente"
           class="btn transicao">
        NOVO CLIENTE</a>
      </div>
    </div>

    @include('clients.search')

    <div class="lista-tabela">
    @if(!$clients->total())
    <div class="alert alert-success" 
         role="alert"
         style="margin-top: 20px;">
      <p>Nenhum registro encontrado.</p>
    </div>
    @else
      <table class="table table-hover borda-topo-cinza">
        <thead>
          <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Telefone</th>
            <th>E-mail</th>
            <th colspan="2">Ações</th>
          </tr>
        </thead>
        <tbody>
          @foreach($clients as $client)
          <tr>
            <td>{{ $client->id }}</td>
            <td>{{ $client->name }}</td>
            <td>{{ $client->cellphone }}</td>
            <td>{{ $client->email }}</td>
            <td>
              <a href="javascript:void(0)" 
                 onclick="SximoModal('{{{ route('clientes.edit', ['id' => $client->id] ) }}}', 'Editar de Clientes')" 
                 title="Editar"><i class="fa fa-edit"></i></a>
              <a href="javascript: void(0)" 
                 class="remove" 
                 data-id="{{ $client->id }}"
                 title="Excluir atividade"><i class="fa fa-close"></i></a>
            </td>
          </tr>
          @endforeach
        </tbody>
        <tfoot>
          <tr>
            <td colspan="7">
              {{ $clients->links('vendor.pagination.default') }}
            </td>
          </tr>
        </tfoot>
      </table>
    @endif
    </div>
  </div>

@endsection

resources/views/clients/search.blade.php
<form class="form-inline frm-busca">
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <div class="input-group">
          <input type="input" size="100" name="search" id="buscar-atividade" class="form-control" value="{{ request()->get('search', null) }}" placeholder="Busca" />
          <div class="input-group-addon">
            <i class="fa fa-search"></i>
          </div>
        </div>
      </div>
    </div>

    <div class="col-sm-12 col-md-8">
      <div class="form-group">
        <label for="status">Tipo:</label>
        <select name="type_profile" class="form-control">
          <option value="">Selecione: </option>
          <option value="F" {{ request()->get('type_profile', null) == 'F' ? 'selected' : null  }}>Pessoa Física</option>
          <option value="J" {{ request()->get('type_profile', null) == 'J' ? 'selected' : null  }}>Pessoa Jurídica</option>
          
        </select>
      </div>
      @role(['diretoria', 'ti'])
      <div class="form-group">
        <label for="status">Colaborador:</label>
        <select name="collaborator_id" class="form-control">
          <option value="">Selecione: </option>
          @foreach(getCollaborators() as $collaborator)
          <option value="{{$collaborator->id}}" {{ request()->get('collaborator_id', 0) == $collaborator->id ? 'selected' : null  }}>{{$collaborator->name}}</option>
          @endforeach
        </select>
      </div>
      @endrole

      <div class="form-group">
        <button class="btn btn-buscar transicao">BUSCAR</button>
      </div>
    </div>
  </div>
</form>